// DO NOT EDIT THIS FILE

#include <iostream>

#include "player.hpp"

int main()
{
  // create one instance of player using default constructor
  Player p1;
  // create another instance of player using non-default constructor
  Player p2("Mary", 20, 10, 6, 0, 0);

  // move player p1 ten times
  for (int i = 0; i < 10; i++) {
    p1.playerMove();
  }

  // test the routines to display stats and take damage
  p1.displayStat();
  std::cout << "\n";

  p2.displayStat();
  std::cout << "\n";

  p1.takeDamage(25);
  std::cout << "\n";

  p1.displayStat();

  return 0;
}
